site_name: Documentazione Prodotti
nav: {{nav}}
theme:
  name: material
  palette:
    primary: indigo
    accent: indigo
  language: it
  logo: Null
  features:
    # - navigation.tabs
    - navigation.sections
    - navigation.top
markdown_extensions:
  - admonition
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
extra:
  # homepage: http://example.com/
  generator: false
  version: 1.0.0
copyright: Copyright &copy; 2021
docs_dir: ''
site_dir: '../docs'
