site_name: Documentazione Prodotti
nav: 
- Home: index.md
- 1. Elettronica Interno Quadro:
  - 2. Automazione:
    - 1. Micro PLC: files/1-2-1.md
    - 2. PLC: files/1-2-2.md
- 2. Elettromec. Interno Quadro:
  - 2. Sezionamento:
    - 1. Sezionatori: files/2-2-1.md
  - 6. Dialogo Operatore:
    - "2. Pulsanteria \xEF\xBF\xBD22": files/2-6-2.md
    - 4. Segnalazione: files/2-6-4.md
- 4. Elettromecc. Bordo Macc.:
  - 2. Connettori Sensori:
    - 1. Connettori Sensori: files/4-2-1.md
  - 3. Connettori Industriali:
    - 1. Connettori Industriali: files/4-3-1.md
  - 7. Cavi Automazione:
    - 1. Cavi Automazione: files/4-7-1.md

theme:
  name: material
  palette:
    primary: indigo
    accent: indigo
  language: it
  logo: Null
  features:
    # - navigation.tabs
    - navigation.sections
    - navigation.top
markdown_extensions:
  - admonition
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
extra:
  # homepage: http://example.com/
  generator: false
  version: 1.0.0
copyright: Copyright &copy; 2021
docs_dir: ''
site_dir: '../docs'
